image: node:latest
before_script:
  - npm install
stages:
  - build
  - test
  - deploy
build:
  stage: build
  script:
    - npm run build
  only:
    - master
  tags:
    - dev
test:
  stage: test
  script:
    - npm run test
  only:
    - master
  tags:
    - docker
deploy:
  stage: deploy
  script:
    - echo "deploy ..."
  only:
    - master
  tags:
    - shell
