stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - cnpm run build
  only:
    - master

test:
  stage: test
  script:
    - test
  only:
    - master

deploy:
  stage: deploy
  script:
     - deployuitp
  only:
     - master

