stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "We should build something."
  only:
    - master

test:
  stage: test
  script:
    - echo "test..."
  only:
    - master

deploy:
  stage: deploy
  script:
     - echo "deployutip..."
  only:
     - master

